#!/bin/sh

if test $# -ne 0
then echo >&2 "$0: ignoring args"
fi

if pgrep -x 'ssh-agent' > /dev/null
then
	echo >&2 "$0: ssh-agent already running"
	exit 1
fi

ENV_PATH="$HOME/.ssh/env_agent"

ssh-agent -t1h 2>&1 | sed '/^echo/d' | tee "$ENV_PATH"

. "$ENV_PATH"
