#!/bin/sh

set -e

if test $# -ne 0
then echo >&2 "$0: ignoring args"
fi

if pgrep -x 'ssh-agent' > /dev/null
then
	echo >&2 "$0: ssh-agent already running"
	exit 1
fi

ENV_PATH="$HOME/.ssh/env_agent"

ssh-agent -t4h 2>&1 | sed '/^echo/d' | tee "$ENV_PATH"

. "$ENV_PATH"

if tmux info >/dev/null 2>&1
then
	echo >&2 "$0: updating tmux env"

	sed 's/;.*//' < "$ENV_PATH" |
		while IFS== read name val
		do tmux set-environment -g "$name" "$val"
		done
fi
