#!/bin/sh

set -e

usage(){
	echo >&2 "Usage: $0 [z] [tmux-resurrect]"
	exit 2
}

cd ~/.config/dotfiles/
mkdir -p contrib
cd contrib

if test $# -eq 0
then set -- z tmux-resurrect
fi

for arg
do
	case "$arg" in
		z)
			git clone https://github.com/bobrippling/z
			;;
		tmux-resurrect)
			git clone https://github.com/tmux-plugins/tmux-resurrect
			;;
		*)
			usage
			;;
	esac
done
