#!/bin/sh

# this script can be used should the host not support symlinking into the git repo

usage(){
    echo >&2 "Usage: $0 install|collect|diff" >&2
    exit 2
}

if test $# -ne 1
then usage
fi

case "$1" in
    install|collect|diff)
        direction="$1"
        ;;
    *)
        usage
        ;;
esac

clrtoeol='\x1b[2K'

find . -type f \
    | sed '/\.git\//d; /.vim\/undo\//d' \
    | while read f
    do
        template=$(echo $f | sed 's;tiny/;;')

        installed=~/"$template"

        printf '\x1b[2Kchecking if %s exists...\r' "$template" >&2

        if ! test -e "$installed"
        then continue
        fi

        printf "$clrtoeol"'comparing %s...\r' "$template" >&2

        if cmp "$installed" $f >/dev/null 2>&1
        then continue
        fi

        case $direction in
            collect)
                cp "$installed" $f
                printf "$clrtoeol"'collected %s\n' "$f" >&2
                ;;
            install)
                cp $f "$installed"
                printf "$clrtoeol"'installed %s\n' "$f" >&2
                ;;
            diff)
                printf "$clrtoeol" >&2
                diff -u $f "$installed"
                ;;
        esac
    done

printf '\x1b[2K\r' >&2
