#!/bin/sh

# this script can be used should the host not support symlinking into the git repo

usage(){
    echo >&2 "Usage: $0 install|collect" >&2
    exit 2
}

if test $# -ne 1
then
    usage
elif test "$1" = install
then direction=install
elif test "$1" = collect
then direction=collect
else usage
fi

clrtoeol='\x1b[2K'

find . -type f \
    | sed '/\.git\//d' \
    | while read f
    do
        template=$(echo $f | sed 's;tiny/;;')

        printf '\x1b[2Kchecking if %s exists...\r' $template

        if ! test -e ~/$template
        then continue
        fi

        printf "$clrtoeol"'comparing %s...\r' $template

        if cmp ~/$template $f >/dev/null 2>&1
        then continue
        fi

        case $direction in
            collect)
                cp ~/$template $f
                printf "$clrtoeol"'collected %s\n' "$f"
                ;;
            install)
                cp $f ~/$template
                printf "$clrtoeol"'installed %s\n' "$f"
                ;;
        esac
    done

printf '\x1b[2K\r'
