#!/bin/sh

cd

#xsetroot -solid grey
randomwallpaper.sh
xset r rate 200 25

#urxvtd -q -f -o
#urxvtc -ls &
urxvt&

dwm="$HOME/src/Suckless/dwm/extra"
. $dwm/env
randomwallpaper.sh

exec $dwm/dwm_run.sh
