#!/bin/sh

remote_name="$1"
remote_dest="$2" # maybe == $1

ec=0

# refs/heads/local-br 1234... refs/heads/master (9982...|000000...)
# (delete)            0000... refs/heads/master (9982...|000000...)
# HEAD~3^2...         1234... refs/heads/master (9982...|000000...)
while read local_ref local_sha remote_ref remote_sha
do
	if test "$local_ref" = "(delete)"
	then continue
	fi

	upstream="$remote_name/$(echo "$remote_ref" | sed 's;refs/heads/;;')"
	range="$upstream..$local_ref"
	#echo >&2 "$0: scanning $range ($(git rev-list --count $range) commits)"

	# check we've no local-only commits:
	if git log -i -E --grep '\b(wip|squash|fixup|local|no.*push)\b' --oneline "$range" -- \
		| grep --color=never .
	then
		echo >&2 "commit range \"$range\" contains wip/fixup/squash commits (listed above)"
		ec=1
	fi
done

exit $ec
