live_config_reload = true
log_level = "Warn"

[colors.bright]
black = "0xbcbcbc"
blue = "0xd75f00"
cyan = "0x005faf"
green = "0xd70087"
magenta = "0xd75f00"
red = "0xd70000"
white = "0x005f87"
yellow = "0x8700af"

[colors.cursor]
cursor = "0x444444"
text = "0xeeeeee"

[colors.normal]
black = "0x111111"
blue = "0x0087af"
cyan = "0x005fb7"
green = "0x008700"
magenta = "0xff87b7"
red = "0xaf0000"
white = "0xffffff"
yellow = "0x5f8700"

[colors.primary]
background = "0xeeeeee"
foreground = "0x444444"

[cursor]
unfocused_hollow = true

[[hints.enabled]]
command = "open"
post_processing = true
regex = "(mailto:|https:|http:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.mouse]
enabled = true
mods = "Control"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Command|Control"

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "None"
mouse = "Middle"

[schemes.cobalt2.bright]
black = "#555555"
blue = "#5555ff"
cyan = "#6ae3fa"
green = "#3bd01d"
magenta = "#ff55ff"
red = "#f40e17"
white = "#ffffff"
yellow = "#edc809"

[schemes.cobalt2.cursor]
cursor = "#f0cc09"
text = "#fefff2"

[schemes.cobalt2.normal]
black = "#000000"
blue = "#1460d2"
cyan = "#00bbbb"
green = "#38de21"
magenta = "#ff005d"
red = "#ff0000"
white = "#bbbbbb"
yellow = "#ffe50a"

[schemes.cobalt2.primary]
background = "#132738"
foreground = "#ffffff"

[schemes.cobalt2.selection]
background = "#18354f"
text = "#b5b5b5"

[schemes.papercolor_light.bright]
black = "0xbcbcbc"
blue = "0xd75f00"
cyan = "0x005faf"
green = "0xd70087"
magenta = "0xd75f00"
red = "0xd70000"
white = "0x005f87"
yellow = "0x8700af"

[schemes.papercolor_light.cursor]
cursor = "0x444444"
text = "0xeeeeee"

[schemes.papercolor_light.normal]
black = "0x111111"
blue = "0x0087af"
cyan = "0x005fb7"
green = "0x008700"
magenta = "0xff87b7"
red = "0xaf0000"
white = "0xffffff"
yellow = "0x5f8700"

[schemes.papercolor_light.primary]
background = "0xeeeeee"
foreground = "0x444444"

[schemes.solarized_dark.bright]
black = "#002b36"
blue = "#839496"
cyan = "#93a1a1"
green = "#586e75"
magenta = "#6c71c4"
red = "#cb4b16"
white = "#fdf6e3"
yellow = "#657b83"

[schemes.solarized_dark.cursor]
cursor = "#839496"
text = "#002b36"

[schemes.solarized_dark.normal]
black = "#073642"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
red = "#dc322f"
white = "#eee8d5"
yellow = "#b58900"

[schemes.solarized_dark.primary]
background = "#002b36"
foreground = "#839496"

[schemes.solarized_light.bright]
black = "#002b36"
blue = "#469bf2"
cyan = "#2aa1c8"
green = "#189b25"
magenta = "#6c71c4"
red = "#cb4b16"
white = "#fdf6e3"
yellow = "#c59900"

[schemes.solarized_light.normal]
black = "#073642"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
red = "#dc322f"
white = "#eee8d5"
yellow = "#b58900"

[schemes.solarized_light.primary]
background = "#fdf6e3"
foreground = "#586e75"

[schemes.zenburn.bright]
black = "#656565"
blue = "#87ceeb"
cyan = "#ffd700"
green = "#55ff55"
magenta = "#ff55ff"
red = "#ff5555"
white = "#ffffff"
yellow = "#ffff55"

[schemes.zenburn.cursor]
cursor = "#00ff00"
text = "#000000"

[schemes.zenburn.normal]
black = "#6d6d6d"
blue = "#96853f"
cyan = "#ffa0a0"
green = "#98f898"
magenta = "#ffdead"
red = "#ff3333"
white = "#f5deb3"
yellow = "#f0e68c"

[schemes.zenburn.primary]
background = "#333333"
bright_background = "#555555"
bright_foreground = "#ffffff"
foreground = "#ffffff"

[selection]
save_to_clipboard = false

[window]
decorations = "full"
